name:                tn
version:             0.9.5.0
github:              "massung/tournesol"
license:             BSD3
author:              "Jeffrey Massung"
maintainer:          "massung@gmail.com"
copyright:           "2022 Jeffrey Massung"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/massung/tournesol#readme>

dependencies:
- base
- case-insensitive
- cmdargs
- containers
- data-default
- errors
- extra
- file-embed
- haskeline
- mtl
- parsec
- vector

library:
  source-dirs: src

executables:
  tn:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - tn

tests:
  tn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - tn
