name: tn
version: 0.1.0.0
github: "massung/tn"
license: BSD-3-Clause
author: "Jeffrey Massung"
maintainer: "massung@gmail.com"
copyright: "2024 Jeffrey Massung"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/massung/tn#readme>

dependencies:
  - rerebase
  - algebraic-graphs
  - cmdargs
  - extra
  - file-embed
  - haskeline
  - parsec
  - safe
  - streamly

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  tn-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O
    dependencies:
      - tn

tests:
  tn-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - QuickCheck
      - tn
